# **************************************************************************
# *
# * Authors:     Marta Martinez (mmmtnez@cnb.csic.es)
# *              Roberto Marabini (roberto@cnb.csic.es)
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************
from pwem.protocols import EMProtocol

from pwem.objects import AtomStruct
from pwem.convert.symmetry import  Icosahedron
from pyworkflow.protocol.params import (EnumParam,
                                        IntParam,
                                        MultiPointerParam,
                                        PointerParam,
                                        StringParam,
                                        LEVEL_ADVANCED)


from pwem.constants import (SYM_I222, SYM_I222r, SYM_In25, SYM_In25r,
                                     SYM_I2n3, SYM_I2n3r, SYM_I2n5, SYM_I2n5r,
                                     SCIPION_SYM_NAME)
import numpy as np
from pwem.convert.atom_struct import AtomicStructHandler, fromCIFTommCIF

LOCAL_SYM_NAME = {}
LOCAL_SYM_NAME[SYM_I222] = 'I1'
LOCAL_SYM_NAME[SYM_I222r] = 'I2'
LOCAL_SYM_NAME[SYM_In25] = 'I3'
LOCAL_SYM_NAME[SYM_In25r] = 'I4'
LOCAL_SYM_NAME[SYM_I2n3] = 'I5'
LOCAL_SYM_NAME[SYM_I2n3r] = 'I6'
LOCAL_SYM_NAME[SYM_I2n5] = 'I7'
LOCAL_SYM_NAME[SYM_I2n5r] = 'I8'

class ProtAtomStrucConvertSymmetry(EMProtocol):
    """
    Converts atomic structures between different icosahedral symmetry
    conventions commonly used in cryo-EM and structural biology workflows.
    The protocol allows the same biological assembly to be represented in
    alternative symmetry coordinate systems while preserving the structural
    integrity of the atomic model. More info:
    https://github.com/I2PC/xmipp-portal/wiki/SymmetrySymmetry

    AI Generated:

    Atomic Structure Symmetry Converter (ProtAtomStrucConvertSymmetry) -
    User Manual

        Overview

        The Atomic Structure Symmetry Converter protocol is intended for
        transforming atomic models between alternative icosahedral symmetry
        conventions. In cryo-EM structural biology, large macromolecular
        assemblies such as viral capsids, protein cages, and highly symmetric
        nanoparticles are often described using different coordinate systems
        depending on the reconstruction software, refinement package, or
        visualization environment. This protocol provides a reliable way to
        convert atomic structures from one symmetry orientation convention to
        another while maintaining the biological arrangement of the assembly.

        The protocol is particularly useful when integrating structures and
        maps generated by different software ecosystems that adopt distinct
        definitions of icosahedral symmetry axes. Although the biological
        object itself remains unchanged, differences in coordinate conventions
        can complicate visualization, fitting, refinement, or comparison
        between datasets. The purpose of this protocol is to standardize those
        representations so that downstream analyses can proceed consistently.

        Biological Context and Typical Applications

        Icosahedral symmetry is widely encountered in structural biology,
        especially in studies of viruses and self-assembling macromolecular
        complexes. Different image-processing and modeling platforms may use
        alternative orientations for symmetry axes, resulting in structures
        that appear rotated relative to one another despite describing the
        same particle.

        This protocol becomes especially important when combining cryo-EM
        maps and atomic models originating from separate software pipelines.
        For example, a user may refine a structure in one package while the
        experimental density map was reconstructed using another convention.
        Without symmetry conversion, direct comparison between the two may
        become difficult or misleading.

        The protocol is also valuable during deposition preparation,
        collaborative projects, comparative structural analysis, or when
        transferring models between visualization tools that rely on distinct
        symmetry definitions.

        Symmetry Conventions and Coordinate Systems

        Icosahedral assemblies can be represented using several equivalent
        coordinate systems that differ in the orientation of symmetry axes.
        These conventions do not alter the molecular geometry or biological
        identity of the structure, but they do affect how the assembly is
        positioned and oriented in three-dimensional space.

        The protocol allows users to specify both the original symmetry
        convention and the desired target convention. The resulting atomic
        structure is reoriented accordingly so that it becomes compatible with
        the selected framework.

        From a practical perspective, understanding the symmetry convention
        used during reconstruction and refinement is essential for accurate
        interpretation. Misaligned conventions can produce apparent rotational
        discrepancies between structures and maps even when both correspond to
        the same biological particle.

        Integration With Cryo-EM Workflows

        In cryo-EM workflows, symmetry conversion is frequently required
        before rigid-body fitting, map visualization, local refinement, or
        comparative analysis. Ensuring that all datasets share the same
        coordinate convention simplifies interpretation and reduces the risk
        of orientation-related errors.

        The protocol is especially useful when importing external structures
        into Scipion-based processing environments or exporting refined models
        for use in external software. Standardizing symmetry orientation early
        in the workflow often improves reproducibility and facilitates
        collaboration across research groups.

        Outputs and Interpretation

        After conversion, the protocol produces a new atomic structure
        expressed in the selected target symmetry convention. The transformed
        structure remains biologically equivalent to the original assembly,
        but its coordinate frame becomes compatible with the desired symmetry
        orientation.

        The resulting structure can be used directly for visualization,
        fitting into density maps, structural comparison, or downstream
        refinement. Because only the coordinate convention changes, no
        biological modifications are introduced into the atomic model itself.

        Practical Recommendations

        Before performing symmetry conversion, users should verify the
        symmetry convention associated with both the input structure and any
        target maps or processing software. Confusion between conventions is
        common in icosahedral cryo-EM projects and can lead to apparent
        mismatches during visualization or fitting.

        Visual inspection after conversion is strongly recommended,
        particularly when preparing figures, fitting structures into maps, or
        combining results from different software packages. Consistent
        orientation across datasets greatly simplifies interpretation and
        communication.

        For collaborative projects and long processing pipelines, documenting
        the symmetry convention used at each stage improves reproducibility
        and reduces ambiguity during downstream analyses.

        Final Perspective

        Symmetry conversion is a technically subtle but biologically important
        operation in structural virology and cryo-EM analysis of symmetric
        assemblies. Although the molecular structure itself remains unchanged,
        correct alignment of symmetry conventions is essential for accurate
        map interpretation, fitting, refinement, and visualization. Careful
        management of coordinate systems helps ensure consistency and
        reliability throughout integrative structural biology workflows.
    """
    _label = 'convert_sym'
    _program = ""

    def _defineParams(self, form):
        form.addSection(label='Input')
        form.addParam('pdbFileToBeRefined', PointerParam, pointerClass="AtomStruct",
                       label='Atomic Structure:', allowsNull=True,
                       important=True,
                       help="Input the atomic structure to be modified.")

        form.addParam('originSymmetryGroup', EnumParam,
                       choices=[LOCAL_SYM_NAME[SYM_I222] +
                                " (" + SCIPION_SYM_NAME[SYM_I222] + ")",
                                LOCAL_SYM_NAME[SYM_I222r] +
                                " (" + SCIPION_SYM_NAME[SYM_I222r] + ")",
                                LOCAL_SYM_NAME[SYM_In25] +
                                " (" + SCIPION_SYM_NAME[SYM_In25] + ")",
                                LOCAL_SYM_NAME[SYM_In25r] +
                                " (" + SCIPION_SYM_NAME[SYM_In25r] + ")",
                                LOCAL_SYM_NAME[SYM_I2n3] +
                                " (" + SCIPION_SYM_NAME[SYM_I2n3] + ")",
                                LOCAL_SYM_NAME[SYM_I2n3r] +
                                " (" + SCIPION_SYM_NAME[SYM_I2n3r] + ")",
                                LOCAL_SYM_NAME[SYM_I2n5] +
                                " (" + SCIPION_SYM_NAME[SYM_I2n5] + ")",
                                LOCAL_SYM_NAME[SYM_I2n5r] +
                                " (" + SCIPION_SYM_NAME[SYM_I2n5r] + ")"
                                ],
                       default=SYM_I222r - SYM_I222,
                       label="Symmetry",
                       help="Select the current symmetry of your atomic structure./n"
                            "See https://github.com/I2PC/xmipp-portal/wiki/Symmetry"
                            "Symmetry for a description of the symmetry groups "
                       )

        form.addParam('targetSymmetryGroup', EnumParam,
                  choices=[LOCAL_SYM_NAME[SYM_I222] +
                           " (" + SCIPION_SYM_NAME[SYM_I222] + ")",
                           LOCAL_SYM_NAME[SYM_I222r] +
                           " (" + SCIPION_SYM_NAME[SYM_I222r] + ")",
                           LOCAL_SYM_NAME[SYM_In25] +
                           " (" + SCIPION_SYM_NAME[SYM_In25] + ")",
                           LOCAL_SYM_NAME[SYM_In25r] +
                           " (" + SCIPION_SYM_NAME[SYM_In25r] + ")",
                           LOCAL_SYM_NAME[SYM_I2n3] +
                           " (" + SCIPION_SYM_NAME[SYM_I2n3] + ")",
                           LOCAL_SYM_NAME[SYM_I2n3r] +
                           " (" + SCIPION_SYM_NAME[SYM_I2n3r] + ")",
                           LOCAL_SYM_NAME[SYM_I2n5] +
                           " (" + SCIPION_SYM_NAME[SYM_I2n5] + ")",
                           LOCAL_SYM_NAME[SYM_I2n5r] +
                           " (" + SCIPION_SYM_NAME[SYM_I2n5r] + ")"
                           ],
                  default=SYM_I222 - SYM_I222,
                  label="Symmetry",
                  help="Select the desired symmetry of your atomic structure.\n"
                       "See https://github.com/I2PC/xmipp-portal/wiki/Symmetry"
                       "Symmetry for a description of the symmetry groups "
                  )

    # --------------------------- INSERT steps functions --------------------
    def _insertAllSteps(self):
        origSym = self.originSymmetryGroup.get() + SYM_I222
        targetSym = self.targetSymmetryGroup.get() + SYM_I222
        self._insertFunctionStep('applyTransformationStep',origSym, targetSym)

    def applyTransformationStep(self, origSym, targetSym):
        matrix = self.getTransformationMatrix(origSym, targetSym)

        originAtomStructFn = self.pdbFileToBeRefined.get().getFileName()
        targetAtomStructFn = self._getExtraPath("outPutAtomStruct.cif")
        self.rotateAtomStruct(inAtomStructFn=originAtomStructFn,
                              outAtomStructFn=targetAtomStructFn,
                              matrix=matrix)
        self.createOutputStep(targetSym, targetAtomStructFn)

    def getTransformationMatrix(self, origin, target):
        "compute matrix that converts between two icosahedal simmetries"
        ico = Icosahedron(orientation = SCIPION_SYM_NAME[origin][1:])
        matrix = ico.coordinateSystemTransform(SCIPION_SYM_NAME[origin][1:],
                                               SCIPION_SYM_NAME[target][1:])
        return np.array(matrix)

    def rotateAtomStruct(self, inAtomStructFn, outAtomStructFn, matrix):
        "apply rotation matrix to input atomic structure"

        atSH = AtomicStructHandler(inAtomStructFn)
        atSH.transform(matrix)
        atSH.write(outAtomStructFn)

    def createOutputStep(self, targetSym, targetAtomStructFn):
        """ save new atomic structure"""
        pdb = AtomStruct()
        pdb.setFileName(targetAtomStructFn)
        # MM: to get appropriate cif files to be visualize with Chimera
        # Transform the output cif file in mmcif
        log = self._log
        fromCIFTommCIF(pdb.getFileName(), pdb.getFileName(), log)
        self._defineOutputs(rotatedAtomStruct=pdb)
        self._defineSourceRelation(self.pdbFileToBeRefined, pdb)

    # --------------------------- UTILS functions ------------------

    def _validate(self):
        errors = []
        return errors

    def _summary(self):
        summary = []
        return summary

#    def _citations(self):
#        return ['Cock2009']