# **************************************************************************
# *
# * Authors: Daniel Del Hoyo (ddelhoyo@cnb.csic.es)
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 3 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

import os, shutil
import numpy as np
import itertools

from pyworkflow.protocol.params import FloatParam, PointerParam, EnumParam, BooleanParam, \
    STEPS_PARALLEL, StringParam
from pyworkflow.object import Float, String
from pwem.protocols import EMProtocol
from pwem.convert.atom_struct import toPdb, toCIF, AtomicStructHandler, addScipionAttribute
from pwem.objects import AtomStruct, SetOfAtomStructs

class ProtRMSDAtomStructs(EMProtocol):
    """
    Calculates structural similarity measurements between multiple atomic
    models by evaluating the root mean square deviation (RMSD) across all
    pairwise combinations. The protocol is intended for structural validation
    and comparison workflows in cryo-EM and structural biology, where several
    fitted or refined atomic models must be evaluated against the same
    experimental density map or biological state.

    AI Generated:

    RMSD Validate Map (ProtRMSDAtomStructs) — User Manual
        Overview

        The RMSD Validate Map protocol evaluates the structural consistency
        of a collection of atomic models by computing RMSD values between all
        possible pairs of structures. Its main objective is to quantify how
        similar the conformations are, both globally and at the residue level,
        in order to assess the reliability and reproducibility of atomic
        interpretations associated with a density map.

        In practical cryo-EM workflows, this type of analysis is especially
        useful when several independently refined models exist for the same
        reconstruction, when comparing models generated by different software
        packages, or when validating structural variability observed during
        refinement. The protocol provides both an overall structural deviation
        and a residue-by-residue variability profile, allowing biological users
        to distinguish rigid regions from flexible or uncertain areas.

        Biological Context and Interpretation

        RMSD analysis is widely used as an indicator of structural agreement.
        Low RMSD values generally indicate that different models converge
        toward a similar conformation, suggesting that the interpreted density
        is robust and reproducible. Higher RMSD values may reflect biological
        flexibility, local uncertainty in the map, conformational heterogeneity,
        or differences introduced during refinement.

        Per-residue RMSD measurements are often even more informative than the
        global value because they identify which specific regions vary across
        models. Flexible loops, mobile domains, termini, or poorly resolved
        regions frequently display elevated RMSD values, whereas well-defined
        structural cores tend to remain highly consistent.

        Inputs and Structural Requirements

        The protocol requires a set of atomic structures in PDB or mmCIF format.
        All structures should correspond to the same biological assembly and
        should ideally contain comparable residue numbering and chain organization.
        Structures with inconsistent topology, missing chains, or substantially
        different residue definitions may produce biologically misleading RMSD
        values.

        In most workflows, the structures originate from independent fitting,
        flexible refinement, comparative modeling, or alternative reconstruction
        strategies. The protocol assumes that all models represent comparable
        conformational states and that meaningful residue correspondence exists
        among them.

        Chain Selection and Biological Focus

        Users may optionally restrict the RMSD calculation to selected chains.
        This becomes particularly important in large assemblies where only a
        subset of the structure is biologically relevant for the analysis.
        Examples include focusing on a catalytic subunit, a receptor-binding
        domain, a flexible arm, or a membrane-embedded region.

        Restricting the analysis to specific chains can significantly improve
        interpretability because unrelated structural regions or auxiliary
        components may otherwise dominate the global RMSD value. For symmetric
        assemblies or multi-chain complexes, careful chain selection is often
        essential for meaningful comparisons.

        Atom Selection Strategies

        The protocol allows RMSD calculations using alpha carbons only,
        backbone atoms, or all atoms. This choice strongly influences the
        biological interpretation of the results.

        Alpha-carbon analysis provides a simplified representation of the
        protein fold and is generally the most robust strategy for comparing
        overall conformational changes. It is particularly useful for medium-
        or low-resolution cryo-EM maps where side-chain positioning may not
        be reliable.

        Backbone-based analysis offers a more detailed representation while
        remaining relatively stable against side-chain noise. This option is
        frequently appropriate for high-quality refinements or comparisons of
        closely related conformations.

        Full-atom analysis provides the most detailed comparison and includes
        side-chain positioning. Although potentially more informative, it is
        also more sensitive to local modeling differences, refinement noise,
        and map quality limitations. Biological interpretation should therefore
        consider the resolution and reliability of the underlying density map.

        Hydrogen Inclusion and Weighting

        The protocol optionally includes hydrogen atoms in the RMSD calculation.
        In most cryo-EM workflows hydrogens are absent or not experimentally
        resolved, so excluding them is generally appropriate. However, in
        high-resolution structural studies or hybrid workflows involving
        crystallography and molecular simulations, hydrogen inclusion may
        become relevant.

        Additional weighting options allow backbone atoms to contribute more
        strongly during the comparison. This can help stabilize the analysis
        when side-chain variability is expected or when the biological question
        focuses primarily on the global fold rather than local rotamer changes.

        Residue-Level Variability Analysis

        One of the most biologically valuable outputs of the protocol is the
        residue-level RMSD annotation. Instead of providing only a single
        structural deviation value, the protocol generates residue-specific
        measurements describing local variability across the full set of models.

        This information is especially useful for identifying flexible regions,
        conformational transitions, ligand-induced rearrangements, or poorly
        resolved domains. Regions with consistently low RMSD often correspond
        to structurally stable cores, while elevated RMSD values may indicate
        biologically dynamic regions or modeling uncertainty.

        These residue-level annotations can later be visualized directly on
        the atomic structures using molecular visualization tools, facilitating
        intuitive interpretation of structural variability.

        Outputs and Their Interpretation

        The protocol produces an output set of annotated atomic structures
        together with an overall average RMSD value summarizing the structural
        agreement among the models. Each structure preserves its original
        geometry while incorporating residue-specific RMSD information that
        can be used for visualization and downstream analysis.

        From a biological perspective, low overall RMSD values support the
        reproducibility of the structural interpretation, whereas elevated
        values suggest either conformational heterogeneity or instability in
        the fitting or refinement process.

        Practical Recommendations

        For most cryo-EM validation workflows, alpha-carbon or backbone RMSD
        calculations provide the most robust and biologically interpretable
        results. Full-atom comparisons are generally more suitable for
        high-resolution datasets where side-chain conformations are reliable.

        Before running the analysis, users should verify that residue numbering,
        chain identities, and overall topology are consistent across all models.
        Inconsistent chain organization is one of the most common causes of
        misleading RMSD measurements.

        When interpreting residue-level RMSD profiles, it is important to
        distinguish between biologically meaningful flexibility and uncertainty
        arising from weak density or incomplete refinement. Visual inspection
        together with map quality assessment is strongly recommended.

        Final Perspective

        Structural reproducibility is a critical aspect of cryo-EM model
        validation. RMSD analysis provides a quantitative framework for
        determining whether multiple structural interpretations converge toward
        a consistent biological solution. By combining global and residue-level
        measurements, this protocol helps identify stable structural cores,
        flexible regions, and areas of uncertainty, ultimately supporting more
        reliable biological conclusions from atomic modeling workflows.
    """

    _label = 'RMSD validate map'
    _ATTRNAME = 'perResidueRMSD'
    _OUTNAME = 'outputAtomStructs'
    _possibleOutputs = {_OUTNAME: SetOfAtomStructs}

    averageRMSDs = []
    combinedResRMSDs = []

    def __init__(self, **kwargs):
        EMProtocol.__init__(self, **kwargs)
        self.stepsExecutionMode = STEPS_PARALLEL

    # -------------------------- DEFINE param functions -----------------------
    def _defineParams(self, form):
        form.addSection(label='Input')
        form.addParam('inputStructureSet', PointerParam,
                      pointerClass="SetOfAtomStructs", allowsNull=False,
                      label='Input atomic structures.',
                      help="Set the atomic structure to be processed.\n"
                           "Supported formats are PDB or mmCIF; this last one"
                           " is especially useful for very large structures.")
        form.addParam('chains', StringParam, default='',
                      label='Chains to perform the RMSD on: ',
                      help='Comma-separated chains to perform the RMSD on.\nIf empty, all chains will be used')

        group = form.addGroup('Atoms')
        group.addParam('considerAtoms', EnumParam, default=0,
                       choices=['CA', 'BackBone', 'All'], label='Atoms to take into account: ',
                       help='Atoms to use in the RMSD calculation')
        group.addParam('weightbb', FloatParam, default=1.0,
                       label='Backbone weight: ', condition='considerAtoms==2',
                       help='Set the resolution of the input volume.')
        group.addParam('hydrogen', BooleanParam, default=False,
                       label='Consider hydrogens: ',
                       help='Consider hydrogens into calculation')

        form.addParallelSection(threads=4, mpi=1)

    # --------------------------- INSERT steps functions ---------------
    def _insertAllSteps(self):
        convId = self._insertFunctionStep('convertInputStep', prerequisites=[])

        rmsdIds = []
        for comboFn in itertools.combinations(self.getInputFileNames(), 2):
            rmsdIds.append(self._insertFunctionStep('calculateRMSDStep', comboFn, prerequisites=[convId]))

        self._insertFunctionStep('createOutputStep', prerequisites=rmsdIds)

    # --------------------------- STEPS functions ----------------------------
    def convertInputStep(self):
        for inFn in self.getInputFileNames():
            if not inFn.endswith('.pdb'):
                name, ext = os.path.splitext(inFn)
                toPdb(os.path.abspath(inFn), self._getExtraPath(os.path.basename(inFn).replace(ext, '.pdb')))
            else:
                shutil.copy(inFn, self._getExtraPath(os.path.basename(inFn)))


    def calculateRMSDStep(self, combo):
        pdbFiles = self.getConvertedFile(combo[0]), self.getConvertedFile(combo[1])

        if self.chains.get().strip() == '':
            chainlist = None
        else:
            chainlist = self.chains.get().split(',')
        P, Pres, self.Preslist = get_coordinates(pdbFiles[0], self.hydrogen.get(), chainlist, self.getRMSDAtoms(),
                                            self.weightbb.get())
        Q, Qres, Qreslist = get_coordinates(pdbFiles[1], self.hydrogen.get(), chainlist, self.getRMSDAtoms(),
                                            self.weightbb.get())
        # checking that files have same number of residues
        if (len(Pres) != len(Qres)):
            exit("Error: files [%s, %s] do not have same number of residues, %i vs. %i" % (
            pdbFiles[0], pdbFiles[1], len(Pres), len(Qres)))
        else:
            self.numRes = len(Qres)

        # Calculate per-residue RMSD
        per_res_rmsd = []
        for i in range(len(Pres)):
            res1 = np.asarray(Pres[i])
            res2 = np.asarray(Qres[i])
            per_res_rmsd.append(rmsd(res1, res2))

        # Calculate overall RMSD
        rmsdval = rmsd(P, Q)
        self.averageRMSDs.append(rmsdval)
        self.combinedResRMSDs.append(per_res_rmsd)
        print("RMSD %s to %s: %.4f" % (os.path.basename(pdbFiles[0]), os.path.basename(pdbFiles[1]), rmsdval))
    
    def createOutputStep(self):
        outStructFileBase = self._getPath('{}.cif')
        overFinalRMSD = np.mean(self.averageRMSDs)
        print("Overall RMSD:", overFinalRMSD)
        rmsdAttrDic = self.getRMSDAttributeDic()

        ASH = AtomicStructHandler()
        outSet = SetOfAtomStructs.create(self._getPath())
        for AS in self.inputStructureSet.get():
            outStructFileName = outStructFileBase.format(os.path.splitext(os.path.basename(AS.getFileName()))[0])
            inpAS = toCIF(AS.getFileName(), self._getTmpPath('inputStruct.cif'))
            cifDic = ASH.readLowLevel(inpAS)
            cifDic = addScipionAttribute(cifDic, rmsdAttrDic, self._ATTRNAME)
            ASH._writeLowLevel(outStructFileName, cifDic)

            outAS = AS.clone()
            outAS.setFileName(outStructFileName)
            outSet.append(outAS.clone())

        outSet.overallRMSD = Float(overFinalRMSD)
        self._defineOutputs(**{self._OUTNAME:outSet})


    # --------------------------- INFO functions ------------------------------
    def _validate(self):
        errors = []
        return errors

    def _summary(self):
        summary = []
        try:
            summary.append('Overall RMSD: {:.4f}\n'.format(float(self.outputAtomStructs.overallRMSD)))
        except:
            summary = ["Overall RMSD not yet computed"]
        return summary

    # --------------------------- UTILS functions ----------------------------
    def getInputFileNames(self):
        fns = []
        for AS in self.inputStructureSet.get():
            fns.append(AS.getFileName())
        return fns
    
    def getInputVolume(self):
        return self.inputStructureSet.get().getFirstItem().getVolume()

    def getConvertedFile(self, inFile):
        name, ext = os.path.splitext(os.path.basename(inFile))
        for file in os.listdir(self._getExtraPath()):
            if name in file:
                return self._getExtraPath(file)

    def getRMSDAtoms(self):
        if self.considerAtoms.get() == 0:
            return 'CA'
        elif self.considerAtoms.get() == 1:
            return 'full'
        else:
            return None

    def getRMSDAttributeDic(self):
        '''Return a dictionary with {spec: value}
        "spec" should be a chimera specifier'''
        combinedResAvgs = []
        # get average per-residue RMSD
        for i in range(self.numRes):
            rmsdval = 0
            for struct in self.combinedResRMSDs:
                rmsdval += struct[i]
            # this gives us mean RMSD for this residue
            rmsdval /= len(self.combinedResRMSDs)
            combinedResAvgs.append(rmsdval)

        attrDic = {}
        for i in range(len(combinedResAvgs)):
            resId = '{}:{}'.format(self.Preslist[i][4], self.Preslist[i][5:].strip())
            attrDic[resId] = str(round(combinedResAvgs[i], 4))
        return attrDic


def rmsd(V, W):
    """
    Calculate Root-mean-square deviation from two sets of vectors V and W.
    """
    D = len(V[0])
    N = len(V)
    rmsd = 0.0
    for v, w in zip(V, W):
        rmsd += sum([(v[i] - w[i]) ** 2.0 for i in range(D)])
    return np.sqrt(rmsd / N)


def get_coordinates(filename, hydrogen, chain=None, backbone=None, weight=1.0):
    """
    Get coordinates from the first chain in a pdb file
    and return a vectorset with all the coordinates.
    """
    atomlist = ["C", "N", "O", "S", "P"]
    if hydrogen:
        atomlist.append("H")

    x_column = None
    V = []

    # resarray contains the coordinates
    resarray = []

    # reslist contains the residue name and number
    reslist = []

    prevres = ""
    with open(filename) as f:
        lines = f.readlines()
        for line in lines:
            #			if line.startswith("TER") or line.startswith("END"):
            if line.startswith("END"):
                break
            if line.startswith("ATOM"):
                # establish backbone atoms
                backatoms = ['N', 'CA', 'C', 'O']

                # if specific chain is specified, only process that chain
                if chain is not None:
                    if line[21] not in chain: continue

                # see if it's a nucleic acid
                if backbone == 'CA': backatoms = ['CA']
                if line[17:20].strip() in ['DA', 'DC', 'DG', 'DT', 'DI', 'A', 'C', 'G', 'U', 'I']:
                    # add P for RNA/DNA
                    backatoms = ["P", "OP1", "OP2", "O3'", "O5'", "C3'", "C4'", "C5'"]
                    if backbone == 'CA': backatoms = ["C3'", "C4'"]
                tokens = line.split()
                # Try to get the residue
                try:
                    res = line[17:27]
                    # if moved to next residue:
                    if res != prevres:
                        reslist.append(res)
                        if prevres != "":
                            resarray.append(presarray)
                        presarray = []
                        prevres = res
                except:
                    exit("Error parsing residue type for the following line: \n%s" % line)
                # Try to get the atomtype
                try:
                    atom = tokens[-1][0]
                    if atom not in atomlist: continue

                    # check if a backbone atom
                    multiplier = weight
                    if line[12:16].strip() not in backatoms:
                        if backbone is not None: continue
                        multiplier = 1.0 / weight

                except:
                    exit("Error parsing atomtype for the following line: \n%s" % line)

                try:
                    x = line[30:38]
                    y = line[38:46]
                    z = line[46:54]
                    V.append(np.asarray([x, y, z], dtype=float) * multiplier)
                    presarray.append(np.asarray([x, y, z], dtype=float) * multiplier)
                except:
                    exit("Error parsing input for the following line: \n%s" % line)
        resarray.append(presarray)

    V = np.asarray(V)
    return V, resarray, reslist